name: CI/CD Pipeline Toolrent


# Se activa al hacer push a main
on:
  push:
    branches: [ main ]

jobs:
  # --- ETAPA 1: BUILD & TEST ---
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven & Run Tests
        run: mvn clean package # Aquí corren tus tests automáticos

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/toolrent-app:latest .
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push ${{ secrets.DOCKER_USERNAME }}/toolrent-app:latest

  # --- ETAPA 2: DEPLOY A STAGING ---
  deploy-staging:
    needs: build-and-test
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Deploy to Local KVM VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}      # Tu URL de túnel o IP Tailscale
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}      # El 2222 que configuramos
          script: |
            # 1. Ir a la carpeta del proyecto
            cd ~/app
            
            # 2. Bajar la nueva imagen (la que acaba de subir el job anterior)
            docker pull ${{ secrets.DOCKER_USERNAME }}/toolrent-app:latest
            
            # 3. Reiniciar solo el contenedor de la app
            docker compose up -d app-toolrent
            
            # 4. Limpiar imágenes viejas (Vital para tus 10GB de disco)
            docker image prune -f

  # --- ETAPA 3: DEPLOY A PRODUCCIÓN (Con aprobación manual) ---
  deploy-production:
    needs: deploy-staging
    runs-on: ubuntu-latest
    environment: production # Esto permite requerir aprobación en GitHub
    steps:
      - name: Deploy to Production Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USER }}
          key: ${{ secrets.PROD_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/toolrent-app:latest
            docker stop toolrent-prod || true
            docker rm toolrent-prod || true
            docker run -d --name toolrent-prod -p 80:8080 ${{ secrets.DOCKER_USERNAME }}/toolrent-app:latest
