name: CI/CD Pipeline Toolrent


# Se activa al hacer push a main4
on:
  push:
    branches: [ main ]

jobs:
  # --- ETAPA 1: BUILD & TEST ---
  build-and-test:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v4

      
      - name: Build and Push Backend Image
        run: |
          cd Backend/demo
          docker build -t ${{ secrets.DOCKER_USERNAME }}/toolrent-app:latest .
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push ${{ secrets.DOCKER_USERNAME }}/toolrent-app:latest

      - name: Build and Push Frontend Image
        run: |
          cd Frontend
          docker build \
            --build-arg VITE_API_URL=${{ vars.VITE_API_URL }} \
            --build-arg VITE_KEYCLOAK_URL=${{ vars.VITE_KEYCLOAK_URL }} \
            -t ${{ secrets.DOCKER_USERNAME }}/toolrent-front:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/toolrent-front:latest

  # --- ETAPA 2: DEPLOY A STAGING ---
  deploy-staging:
    needs: build-and-test
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Connect to Tailscale
        uses: tailscale/github-action@v2
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}

      - name: Deploy to Local KVM VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.SSH_HOST }}      # Aquí va la IP 100.x.x.x de la VM
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          port: 22                           # ¡OJO! Con Tailscale ya no necesitas el 2222, usa el 22 directo
          script: |
            cd ~/app
            docker pull ${{ secrets.DOCKER_USERNAME }}/toolrent-app:latest
            docker pull ${{ secrets.DOCKER_USERNAME }}/toolrent-front:latest
            docker compose up -d
            docker image prune -f

  # --- ETAPA 3: DEPLOY A PRODUCCIÓN (Con aprobación manual) ---
  deploy-production:
    needs: deploy-staging
    runs-on: ubuntu-latest
    environment: production # Esto permite requerir aprobación en GitHub
    steps:
      - name: Deploy to Production Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USER }}
          key: ${{ secrets.PROD_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/toolrent-app:latest
            docker stop toolrent-prod || true
            docker rm toolrent-prod || true
            docker run -d --name toolrent-prod -p 80:8080 ${{ secrets.DOCKER_USERNAME }}/toolrent-app:latest
